### ISSUE TITLE
False result conditional if block when argument is omitted, without using global variable

### ISSUE THREAD

**Issue by astrotim** [stowball/grunt-include-replace-more#2]
Is it possible to have conditional `if` blocks evaluate as `false` when the argument is omitted? 

For example, if your code sample was changed to omit `"afternoon": false`, like so:

```
{{ include('/path/to/include/message.html', {"name": "Joe Bloggs", "morning": true}) }}
```

then this block would not run:

```
{{ if afternoon }}
<p>Good afternoon, {{ name }}!</p>
{{ endif }}
```

I am aware this can be achieved by setting `"afternoon": false` as a global variable, however in the context of our project, it would be far more efficient to skip this step. My question is: can this be acheived without setting a global variable?

Any help in achieving this would be greatly appreciate, of course above and beyond our appreciation for what this task already allows us to do :)

**Comment by stowball** [comment]
Hey Tim

Yeah, this has been on my to-do list for a while because it annoys me too. Now I know others are using the plugin and are having the same issue, it'll give me some impetus to try and fix it :)

I can't promise any timeframe though.

**Comment by stowball** [comment]
Hi Tim

After a long holiday and then starting a new job, I've finally found the time to do this! v1.4.0 in the npm registry now removes any if blocks and their content is the variable value is not `true`.

Enjoy!

**Comment by astrotim** [comment]
Thanks Matt, that's awesome! It will simplify our Gruntfile and make our lives easier.
