### ISSUE TITLE
Remove containing directory

### ISSUE THREAD

**Issue by iamkeir** [stowball/grunt-include-replace-more#4]
Hey,

Thanks for this fork, really helpful.

Question - I have my html files in `html/` and I am includereplacing them into a folder called `build/` but it keeps placing the html files in `build/html/` rather than just `build/`. Is this something I can tweak? I've been playing with docroot but no luck so far.

Settings:
```
// Includes
includereplacemore: {
  global: {
    options: {
      includesDir: 'html/includes/'
    },
    src: ['html/*.html','!html/includes/**/*.html'],
    dest: 'build/'
  }
}
```
Thanks :)

**Comment by stowball** [comment]
Sorry, only just seen this issue, but no, I don't think there is a way to do what you want, sadly

**Comment by iamkeir** [comment]
That's a shame but no worries - thanks for letting me know! :)
